FROM alpine:3.14
#ENV HOST 127.0.0.1 # =$HOST 
RUN apk add --no-cache postgresql-client
RUN apk add --no-cache bash
#COPY script.sh /tmp/script.sh
#ENTRYPOINT psql -h ${HOST}; echo ${HOST}
#ENTRYPOINT sh -c /tmp/script.sh
